### ISSUE TITLE
zentrales Personen- und Ortsregister anlegen

### ISSUE THREAD

**Issue by peterstadler** [gedigiupb/urkunden_upb#10]
* aus den bestehenden Urkunden die Listen extrahieren und zusammenführen
* die bestehenden Verweise in den Urkunden anpassen

**Comment by DennisFriedl** [comment]
**Zentrales Personen- und Ortsregister erstellt.**
**Urkundenauszeichnungen angepasst.**
 Es fehlt noch:

- Register von Urkunde4 muss in Zukunft nachgetragen werden.
- Muss das jetzt irgendwie verbunden werden?
- Soll das in unserem Schema sein? Ist im Moment in TEI-All.
